//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PennState.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public class CatagoryLocation
    {
        [Key]
        public int Id { get; set; }

        //Cat Name  
        public string LocationName { get; set; }

        //represnts Parent ID and it's nullable  
        public int? Pid { get; set; }

        public bool HasChildren { get; set; }

        [ForeignKey("Pid")]
        public virtual CatagoryLocation Parent { get; set; }
        public virtual ICollection<CatagoryLocation> Childs { get; set; }
    }
}
