//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PennState.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PennStateDB : DbContext
    {
        public PennStateDB()
            : base("name=PennStateDB")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Tbl_CatagoryLocations> Tbl_CatagoryLocations { get; set; }
        public virtual DbSet<Tbl_CatagoryOwners> Tbl_CatagoryOwners { get; set; }
        public virtual DbSet<Tbl_CatagoryTypes> Tbl_CatagoryTypes { get; set; }
        public virtual DbSet<Tbl_CatagoryVendors> Tbl_CatagoryVendors { get; set; }
        public virtual DbSet<Tbl_File> Tbl_File { get; set; }
        public virtual DbSet<Tbl_Items> Tbl_Items { get; set; }
        public virtual DbSet<Tbl_Locations> Tbl_Locations { get; set; }
        public virtual DbSet<Tbl_Photo> Tbl_Photo { get; set; }
        public virtual DbSet<Tbl_Roles> Tbl_Roles { get; set; }
        public virtual DbSet<Tbl_SubLocations> Tbl_SubLocations { get; set; }
        public virtual DbSet<Tbl_Users> Tbl_Users { get; set; }
        public virtual DbSet<Tbl_Requests> Tbl_Requests { get; set; }
    }
}
