//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PennState.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Items
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_Items()
        {
            this.Files = new HashSet<Tbl_File>();
            this.Photos = new HashSet<Tbl_Photo>();
        }
    
        public int Id { get; set; }
        public string ItemName { get; set; }
        public int AmountInStock { get; set; }
        public string LocationComments { get; set; }
        public string Manufacturer { get; set; }
        public string CatalogNumber { get; set; }
        public string WebAddress { get; set; }
        public string Vendor { get; set; }
        public string ContactInfo { get; set; }
        public System.DateTime PurchaseDate { get; set; }
        public Nullable<System.DateTime> Added { get; set; }
        public Nullable<System.DateTime> Updated { get; set; }
        public decimal PurchasePrice { get; set; }
        public string ItemType { get; set; }
        public string ItemNotes { get; set; }
        public string UpdatedBy { get; set; }
        public bool IsDeleted { get; set; }
        public int UsrId { get; set; }
        public Nullable<int> LocId { get; set; }
        public Nullable<int> SubId { get; set; }
    
        public virtual Tbl_Locations Location { get; set; }
        public virtual Tbl_SubLocations SubLocation { get; set; }
        public virtual Tbl_Users User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_File> Files { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Photo> Photos { get; set; }
    }
}
